// @generated by protobuf-ts 2.9.1 with parameter server_grpc1
// @generated from protobuf file "api.proto" (syntax proto3)
// tslint:disable
import { Employee } from "./api";
import { Empty } from "./google/protobuf/empty";
import type * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service EmployeeService
 */
export interface IEmployeeService extends grpc.UntypedServiceImplementation {
    /**
     * @generated from protobuf rpc: GetEmployee(google.protobuf.Empty) returns (Employee);
     */
    getEmployee: grpc.handleUnaryCall<Empty, Employee>;
}
/**
 * @grpc/grpc-js definition for the protobuf service EmployeeService.
 *
 * Usage: Implement the interface IEmployeeService and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: IEmployeeService = ...
 * server.addService(employeeServiceDefinition, service);
 * ```
 */
export const employeeServiceDefinition: grpc.ServiceDefinition<IEmployeeService> = {
    getEmployee: {
        path: "/EmployeeService/GetEmployee",
        originalName: "GetEmployee",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => Employee.fromBinary(bytes),
        requestDeserialize: bytes => Empty.fromBinary(bytes),
        responseSerialize: value => Buffer.from(Employee.toBinary(value)),
        requestSerialize: value => Buffer.from(Empty.toBinary(value))
    }
};
